### ISSUE TITLE
Documentation is missing the explicit versions of the Beamdog games it's compatible with.

### ISSUE THREAD

**Issue by GraionDilach** [drake127/randomrolls#1]
Because this is a binary patch (especially because BGEE/BG2EE/IWDEE 2.5->2.6 involved an x86->x64 switch), this should be documented.

**Comment by drake127** [comment]
Good point, I'll add it to the README. I was not around so I don't know the history. Are people still using x86 build?

**Comment by GraionDilach** [comment]
The Apple platform hasn't received the 2.6 patch yet and some people stay on 2.5 because the "resurrection-no-longer-allowed-to-heal-the-living" change.
